---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  labels: 
    tier: frontend
    app: bc16
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 3
  template:
    metadata:
      name: frontend
      labels: 
        name: frontend
        tier: frontend 
        app: bc16
    spec:
      containers:
        - name: fe
          image: sharansripada/fe_upd
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres
  labels: 
    name: postgres
    tier: db
    app: bc16
spec:
  selector:
    matchLabels:
      name: postgres
      tier: db
  template:
    metadata:
      name: postgress
      labels: 
        name: postgres
        tier: db
        app: bc16 
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: "POSTGRES_USER"
              value: "postgres"
            - name: "POSTGRES_PASSWORD"
              value: "postgres"
            - name: "POSTGRES_DB"
              value: "postgres"

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: job
  labels: 
    name: job
    tier: backend
    app: bc16
spec:
  selector:
    matchLabels:
      tier: backend
      name: job
  template:
    metadata:
      name: job
      labels: 
        name: job
        tier: backend
        app: bc16 
    spec:
      containers:
        - name: job-srv
          image: sharansripada/job_upd
          ports:
            - containerPort: 8082
          env:
            - name: "SPRING_DATASOURCE_URL"
              value: "jdbc:postgresql://db:5432/postgres"
            - name: "SPRING_DATASOURCE_USERNAME"
              value: "postgres"
            - name: "SPRING_DATASOURCE_PASSWORD"
              value: "postgres"
            - name: "SPRING_JPA_HIBERNATE_DDL_AUTO"
              value: "update"

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: org
  labels: 
    name: org
    tier: backend
    app: bc16
spec:
  selector:
    matchLabels:
      tier: backend
      name: org
  template:
    metadata:
      name: org
      labels: 
        name: org
        tier: backend
        app: bc16 
    spec:
      containers:
        - name: org-srv
          image: sharansripada/org_srv
          ports:
            - containerPort: 8081
          env:
            - name: "SPRING_DATASOURCE_URL"
              value: "jdbc:postgresql://db:5432/postgres"
            - name: "SPRING_DATASOURCE_USERNAME"
              value: "postgres"
            - name: "SPRING_DATASOURCE_PASSWORD"
              value: "postgres"
            - name: "SPRING_JPA_HIBERNATE_DDL_AUTO"
              value: "update"
           
           




